agarrharr/awesome-cli-apps

- README.md
surge is for deploying web project from the command line.
> Adds surge to list.

- README.md
If you are a GDB user this is going to help you a lot. I hope it's useful.
> Added GDB-Dashboard

- README.md
> Added 2 more CLI projects to the list

- README.md
As discussed in https://github.com/aharris88/awesome-cli/issues/11.
Not sure about the title ("Fun"). Could also be related to math or graphics, but I guess this should be reviewed along with the categories of the whole list.
> Add cli-mandelbrot

- README.md
Just added Hub, you're going to love it, it makes a more powerful interaction with git when working with GitHub. You're going to be able to do everything from terminal and it's maintained by the GitHub Core Team.
> Add Hub to Git

- README.md
If you want me to place `screensaver` under `Screensavers` I can move it.
> Add `battery-level` and `screensaver`

- README.md
Like recommended over her:
https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license
> Add license

- README.md
I recommend adding this. I have used them and think they are really awesome :sparkling_heart:
> Add new category »resources«

- README.md
This is an app coded by myself and fun to use :smile:
> Add itunes-remote

- contributing.md
> Add contributing guidelines :octocat:

- README.md
I hope you agree. 
See The differences:
> Increase readibility by getting ride of empty lines between list items

- README.md
Add doing and a couple of other tools for your consideration.
> Add doing & more

- README.md
@sboudrias prefers to call it Inquirer instead of inquirer, so I updated this.
> Fixed capitalization of Inquirer.js

- README.md
Added [text-meme](https://github.com/beatfreaker/text-meme-cli) under utility list.
> add text-meme

- README.md
Added [mobisplash-cli](https://github.com/samverschueren/mobisplash-cli) to the list of `mobile app development`.
> add mobisplash

- README.md
> Add WP-CLI

- README.md
Hi,
this pull request is for proposing a CLI tool that i've recently created, hoping it would be useful to others like it is for me.
It's written in NodeJS and let the user: 
- Search throughout the wide catalog of fonts provided by Google
- Download a font (also some specific variants) in the desired folder
- Install the font in his system (in Linux and OSX the font are placed in the user font directory, while in Windows they are natively installed with a WScript specifically created for that platform)
https://github.com/lordgiotto/google-font-installer
https://npmjs.com/package/google-font-installer
Thank you :)
> Added google-font-installer under Utilities Section

- README.md
> Add ponysay

- README.md
[Cash](https://github.com/dthree/cash) implements popular Unix / Linux commands such as `ls`, `grep` `less` using straight ES6, installed through Node.
> Add Cash: Cross-platform Linux commands in pure ES6

- README.md
- Added somafm-cli to entertainment section
> Added somafm-cli to entertainment section

- README.md
- Added ramda-cli to data manipulation section
> Added ramda-cli to data manipulation section

- README.md
- Fixed missing space issues which violated contributing guidelines
> Fixed missing space issues which violated contributing guidelines

- README.md
* Added aria2 to utilities section
> Added aria2 to utilities section

- README.md
It's like mkdir, for licenses :baby: 
https://github.com/cezaraugusto/mklicense
> Add mklicense

- README.md
Add [medium-cli](https://github.com/djadmin/medium-cli) to awesome-cli-apps list
> Add Medium CLI

- README.md
> Add htconvert

- README.md
> Add gifgen

- README.md
https://github.com/sahildua2305/github-check-cli
> Add GitHub Check CLI to Git tools

- README.md
Adds [facebook-cli](https://github.com/specious/facebook-cli), which gives you a command line interface to Facebook.
Here's an asciicast:
<a href="https://asciinema.org/a/87129"><img src="https://asciinema.org/a/87129.png" width="400"/></a>
> Add facebook-cli

- README.md
A foreign exchange rates and currency conversion using cli
> add moeda - currency conversion using cli

- README.md
Re-adding [facebook-cli](https://github.com/specious/facebook-cli) (previously added in #70) and [meetup-cli](https://github.com/specious/meetup-cli).
> Add facebook-cli and meetup-cli

- README.md
[bitly-client](https://github.com/specious/bitly-client), a command line tool to help you make and manage [Bitly](https://bitly.com) shortlinks.
> Add bitly-client

- README.md
It's a command line power tool for Jira
> add tejira

- README.md
I changed line.
https://github.com/aharris88/awesome-cli-apps/pull/79
> Added g3l to productivty.

- README.md
Add uber-cli, simply just count time and price, but useful.
> Add Uber CLI

- README.md
> Add rainbowstream

- README.md
[Pocket ](https://getpocket.com)is a really useful tool and I've made a composable, simple command-line client for it - [pockyt](https://github.com/arvindch/pockyt).
Note - It's not exactly social media but couldn't really find the appropriate category.
> Add pockyt

- README.md
fz is the missing fuzzy tab completion feature of z. Check out its [homepage](https://github.com/changyuheng/fz) for more information.
> Add fz - seamless fuzzy tab completion for z

- README.md
Trino CLI allows a quick and easy translation of words and phrases entered in the command line.
> * Add Trino

- README.md
> Add open-pip-cli

- README.md
rename-cli is a tool to rename files and excels at renaming multiple files at once.  It supports glob file matching, variables in the output file name, auto-indexing, and can be customized by the user.  It is written in node and is cross-platform.
https://github.com/jhotmann/node-rename-cli
> Add rename-cli

- README.md
> # MapSCII - The Whole World In Your Console.
> A node.js based [Vector Tile](http://wiki.openstreetmap.org/wiki/Vector_tiles) to [Braille](http://www.fileformat.info/info/unicode/block/braille_patterns/utf8test.htm) and [ASCII](https://de.wikipedia.org/wiki/American_Standard_Code_for_Information_Interchange) renderer for [xterm](https://en.wikipedia.org/wiki/Xterm)-compatible terminals.
– https://github.com/rastapasta/mapscii
> add MapSCII

- README.md
Added new section for virtualization to put dockly under, as none of the others seemed relevant.
> Add dockly

- README.md
A CLI to pull random/queried images from unplash.com and apply to your desktop wallpaper.
**npm:** https://www.npmjs.com/package/jackpaper
> Add JackPaper

- README.md
Calories is a commandline tool for tracking calories and weight using the Harris Benedict formula for calculating your BMR (Basal Metabolic Rate).
I haven't found many health-related tools on the list yet, so I thought it might be a good fit.
[https://github.com/zupzup/calories](https://github.com/zupzup/calories)
> Add calories

- README.md
Hi :) Im still learning git. I hope this is acceptable.
> added calcurse

- README.md
`git-secret` repo: https://github.com/sobolevn/git-secret
`git-secret` site: http://git-secret.io/
> Adds git-secret into git section

- readme.md
Organize CLI allows developers to organize and clean up their folder the way they want.
> Adds organize-cli to file managers section

- readme.md
(https://themer.mjswensen.com)
> Adds themer to development category.

- readme.md
> ipt ... pivotal tracker cli

- readme.md
https://github.com/c0bra/deviceframe
deviceframe wraps mobile/web/etc screenshots in a frame, as you see in app/play store screenshots.
> Add deviceframe cli utility

- readme.md
> Add DeckTape

- readme.md
Link: [HERE](https://github.com/xxczaki/cash-cli)
With cash-cli you can convert 32 currencies directly using your terminal! It is fast & simple :) Just do for example: `cash 10 usd eur` and it will convert 10 Dollars to Euros. 
<p align="center"><img src="https://i.imgur.com/kOhOiBU.gif" alt="Screenshot"></p>
> Added cash-cli

- readme.md
According to issue https://github.com/agarrharr/awesome-cli-apps/issues/162
> Removed Code Sponsor link

- readme.md
Made with [Asciimatics](https://github.com/peterbrittain/asciimatics). Displays "Merry Christmas" and a burning log. Restart the snowfall by pressing enter.
[YuleLog](https://github.com/Duroktar/YuleLog/blob/master/yule_log/screenshot.png)
> Added YuleLog

- readme.md
[🌈](https://github.com/busyloop/lolcat)
> Add lolcat

- readme.md
This adds xiringuito - SSH-based "VPN for poors"
Thanks!
> Add xiringuito - SSH-based "VPN for poors"

- readme.md
<p align="center">
NASA CLI - :rocket: Download NASA Picture of the Day from your terminal!
</p>
[Repo link](https://github.com/xxczaki/nasa-cli)
You can download NASA Picture of the Day, by running: `nasa -t` or you can download NASA Picture of the Day from a specific date, by running `nasa -d YYMMDD`.
> Added nasa-cli

- readme.md
> Add legit to »Development« section

- readme.md
> Added 'grv' to 'git' category

- readme.md
Abides by Contributing guidelines.
> Added stronghold to MacOS section

- readme.md
Added a useful CLI tool that I regularly use.
> Add add-gitignore

- readme.md
I think this tool that I wrote called [eureka](https://github.com/simeg/eureka) would be a good fit in this list. It fits in the _Productivity_ section because with the tool you can store your ideas without leaving the terminal, hence increasing your productivity (assuming you work a lot in the terminal).
> Add productivity CLI tool eureka

- readme.md
PS Can I add gif with fx demo?
> Update fx description

- readme.md
https://github.com/dolsup/cli-fireplace
a digital Fireplace for Xmas.
> add cli-fireplace

- readme.md
If you don't know it: just try and let it simplify your life ;)
> Add pass: simple and powerful cli password manager

- readme.md
Hello,
Maybe we can add this tool here? It's a CLI tool that checks if a domain is up or down, it checks that in a smart way with configurable timeouts, retries, etc. You can also check multiple websites at once like so:
```
reachable check google.com twitter.com facebook.com
```
You just need to download the binary 😄
> Added reachable

- readme.md
This reverts commit c8563b92785868ee86e4150d6f8772d468508594.
> Revert "Added simplehttp (#260)"

- readme.md
Quick and simple image processing at the command line
> added korkut

- readme.md
Neofetch is a command-line system information tool that supports 150+ Operating Systems and Distributions. :+1:
> Added neofetch

- readme.md
[cointop](https://github.com/miguelmota/cointop) - The fastest and most interactive terminal based UI application for tracking cryptocurrencies
> add cointop

- readme.md
This is a TUI based finder for searching the awesome resources on awesome series such as awesome-python, awesome-go and so on.
> Add awesome-finder

- readme.md
This is a HTTP-server to execute shell commands. Designed for development, prototyping or remote control.
> Added shell2http

- readme.md
Github repo: https://github.com/harelba/q
> Add "q" - run SQL directly on CSV or TSV files

- readme.md
- Add mvd CLI app, which is a simple tty markdown viewer
> Markdown viewer

- readme.md
Up: Ultimate Plumber is a tool for writing Linux pipes with instant live preview
> Added Up to the tools section

- readme.md
Features of [z.lua](https://github.com/skywind3000/z.lua):
- **10x** times faster than **fasd** and **autojump**, **3x** times faster than **z.sh**.
- Available for **posix shells**: bash, zsh, dash, sh, ash, busybox and etc.
- Available for Fish Shell, Power Shell and Windows cmd.
- Enhanced matching mode takes you to where ever you want precisely.
- Allow updating database only if `$PWD` changed with "$_ZL_ADD_ONCE" set to 1.
- Interactive selection enables you to choose where to go before cd.
- Interactive selection with FZF (optional).
- Quickly go back to a parent directory instead of typing "cd ../../..".
- Corresponding experience in different shells and operating systems. 
- Compatible with Lua 5.1, 5.2 and 5.3+
- Self contained, distributed as a single `z.lua` script, no other …
> add: z.lua - A new cd command that helps you navigate faster by learning your habits

- readme.md
> Add release subcategory

- readme.md
> Add network utilities subcategory

- readme.md
An interactive command-line HTTP client featuring autocomplete and syntax highlighting.
> Add HTTP Prompt

- readme.md
> Add release

- readme.md
> Add new Emoji subcategory under Other

- readme.md
> Move quote-cli to Just for Fun

- readme.md
> Add Movies category

- readme.md
closes #285 
Completes all moves discussed.
> Add new Theming/Customization subcategory to Utilities

- readme.md
starring is broken ([see my issue from mid 2018](https://github.com/ritz078/starring/issues/11)) and inactive.
And thus should be removed.
> Remove starring

- readme.md
**App name:**transmission-cli
**Repo or homepage link:**[**site**](https://transmissionbt.com/download/)
Full-fetched torrent client for your command line. Can be fully controlled through the cli, also has a gui web-interface.
It's fully scriptable, easy to use and uses few resources.
> Add transmission-cli

- readme.md
**App name:** taskell
**Repo or homepage link:** [repo](https://github.com/smallhadroncollider/taskell)
Command-line Kanban board/task manager with support for Trello boards and GitHub projects taskell.app
- lightweight
- functional
- easy to use
- full color customization
> Add taskell

- readme.md
Groups together presentation apps.
> Add 'presentations' subcategory

- readme.md
**App name:** ffsend
**Repo or homepage link:** https://github.com/timvisee/ffsend
**Description:** ffsend is a fully featured CLI for Firefox Send - a simple and private way to share files with others.
**Why you think it's awesome:** Firefox Send is a great way to share private files for free. This tool is a great way to use the service from the command line. It's still in development but it's very stable and already fully featured. Allows you to securely upload and download files via Firefox Send and supports a range of other features that Firefox Send offers via command line arguments/flags. Also allows you to use Firefox Send within scripts.
> Add ffsend

- readme.md
Adds Taskbook, probably one of the best and most popular terminal todo apps today.
- Repository: https://github.com/klaussinani/taskbook
As discussed at issue #307.
Thank you @klaussinani for this amazing applickation and your work! 🔥
> Add taskbook

- readme.md
**App name:** Kakoune
**Repo or homepage link:** https://github.com/mawww/kakoune and http://kakoune.org
**Description:** mawww's experiment for a better code editor
**Why you think it's awesome:** It takes inspiration from VIM, while being very innovative. And it resurrects Clippy!
> Add kakoune

- readme.md
**App name:** fkill-cli
**Repo or homepage link:** [repo](https://github.com/sindresorhus/fkill-cli)
Simple cross-platform process killer.
The most straight forward process killer I know. Either enter the process name in the interactive mode (with filtering) or pass the process name directly (very scriptable).
> Add fkill-cli

- readme.md
**App name:**
Timewarrior
https://github.com/GothenburgBitFactory/timewarrior
Timewarrior is a time tracking utility that offers simple stopwatch features as well as sophisticated calendar-base backfill, along with flexible reporting. 
Uses ncurses to create amazing graphical reports.
> Add Timewarrior

- readme.md
**App name:** Qalculate!
**Repo or homepage link:** https://github.com/Qalculate/libqalculate
Qalculate! is a multi-purpose cross-platform desktop calculator. It is simple to use but provides power and versatility normally reserved for complicated math packages, as well as useful tools for everyday needs (such as currency conversion and percent calculation). Features include a large library of customizable functions, unit calculations and conversion, physical constants, symbolic calculations (including integrals and equations), arbitrary precision, uncertainty propagation, interval arithmetic, plotting, and a user-friendly interface (GTK+ and CLI).
I'm not the dev of this app, but It's amazing. I have it always running on an i3 scratchpad. …
> Add Qalculate

- ideas.txt
- readme.md
**App name:** gcalcli
**Repo or homepage link:** https://github.com/insanum/gcalcli
**Description:** Access Google calendar from the terminal.
> add gcalcli

- ideas.txt
- readme.md
**App name:** webtorrent-cli
**Repo or homepage link:** https://github.com/feross/webtorrent-cli
**Description:** Feature packed torrent client from your terminal.
**Why you think it's awesome:** It allows for streaming of the torrents being downloaded via local server.
> Add webtorrent-cli

- readme.md
**App name:**
bitwise
https://github.com/mellowcandle/bitwise
Terminal based bitwise calculator in curses.
First, I created it so I'm not objective, but it's very useful to me and my colleagues.
we manipulate bitmasks a lot, and switch between hex/dec representation.
We prefer to stay on terminal and not use web or desktop calculator.
> Add bitwise

- ideas.txt
- readme.md
Addresses [this open issue](https://github.com/agarrharr/awesome-cli-apps/issues/108)
> Add more awesome lists

- readme.md
**App name:** task-spooler
**Repo or homepage link:** [home](http://vicerveza.homeunix.net/~viric/soft/ts)
Queue jobs for linear execution.
It allows me to execute network intensive requests one after the other without block the connection or timing out (like if they were to run in parallel).
I also use it for queuing a bunch of youtube videos at once and then watch them one after the other without manually starting the next one.
> Add task-spooler

- readme.md
> Update broken link for terminal velocity

- readme.md
**App name:**
ipfs-deploy
- Repo: https://github.com/agentofuser/ipfs-deploy
- Homepage: https://interplanetarygatsby.com/ipfs-deploy
Zero-config CLI to deploy static websites to IPFS.
I'm obviously biased, but I built ipfs-deploy because I wanted to host my blog on IPFS, and it was just too much hassle without it. Now anyone can get started with static website deployment on the "dweb" without any prior knowledge.
> Add ipfs-deploy

- readme.md
Removing call for maintainers as the issue is closed.
Fixes #247
> Remove call for maintainers

- readme.md
**App name:** pipe_exec
**Repo or homepage link:** https://github.com/koraa/pipe_exec
**Description:** Run executables from stdin, pipes and ttys without creating a temporary file.
**Why you think it's awesome:** It's a utility I found I needed a couple of times; it's a fundamental utility using the correct system interfaces;
Comparable shell script solutions exist, but they have drastically higher overhead (creating temporary files, firing up a shell interpreter, creating
multiple processes) and usually work less consistently (e.g. if /tmp is mounted as noexec creating a tmp executable file will fail).
> Add pipe_exec

- readme.md
**App name:** cataclysm-dda
**Repo or homepage link:** [home](https://cataclysmdda.org/), [repo](https://cataclysmdda.org/)
Turn-based zombie survival game.
A tense survival game with tons of ever expanding content.
> Add Cataclysm-DDA

- readme.md
Groups utils for working in the shell together.
> Add 'Shell Utilities' subcategory

- readme.md
Bundle scaffolding/bootstrapping/boilerplating utils in one category.
> Add 'Boilerplate' subcategory

- readme.md
Groups together apps that interact with the system.
> Add 'System Interaction Utilities' subcategory

- readme.md
**App name:** dark-mode
**Repo or homepage link:** https://github.com/sindresorhus/dark-mode
**Description:** Toggle macOS's dark mode from the terminal.
> Add dark-mode

- readme.md
All todo words were fixed to TODO.
> Fix TODO case

- readme.md
**App name:** Watson
**Repo or homepage link:** https://github.com/TailorDev/Watson
**Description:** Terminal time tracker that can generate reports for clients and manage your time.
**Why you think it's awesome:** Great time tracker capable of generating reports and providing a simple overview of where time is being spend. Very active developers behind the repositories and its easy to setup.
Note: I'm currently working and unable to access git from a terminal and my understanding is that amending and editing commits is not possible at this time. Please disregard the use of the non-imperative form.
> Add Watson

- readme.md
**App name:** isitfit
**Repo or homepage link:** https://github.com/autofitcloud/isitfit
**Description:** Manage AWS EC2 rightsizing
**Why you think it's awesome:** It's the only tool that does AWS EC2 rightsizing in the terminal
> Add isitfit

- readme.md
**App name:** gitmoji-cli
https://github.com/carloscuesta/gitmoji-cli
This project provides an easy solution for using gitmoji from your command line. Gitmoji-cli solves the hassle of searching through the gitmoji list. Includes a bunch of options you can play with! 🎉
I tend to put emojis in my git commit messages and this tool makes it easier
> Add gitmoji-cli

- readme.md
**App name:** pastel
**Repo or homepage link:** https://github.com/sharkdp/pastel
**Description:** A tool to generate, analyze, convert and manipulate colors.
**Why you think it's awesome:** It handles many color formats (HSL, RGB…) and therefore is a great companion while building themes or tweaking CSS. Also it's made by the same author than bat and fd.
> Add pastel

- readme.md
**App name:** playx
**Repo or homepage link:** [playx](https://github.com/NISH1001/playx)
**Description:** Music assistant for Linux written in Python. It has support to play songs and playlists from various source ranging from spotify to billboard and many other famous sources.
**Why you think it's awesome:** It is awesome because it's the closes thing to a music assistant, all from the terminal. All we need to do is pass an argument about what to stream and it does that.
> Add app playx

- readme.md
**App name:**
groq-cli
https://github.com/sanity-io/groq-cli
Powerful JSON processor. Query and project (ND)JSON documents from stdin.
It's like SQL for JSON. You can query documents/objects to filter down to only those you need, and then project the result into the structure you want. The syntax is easier to learn and remember than other similar tools.
> Add groq-cli

- readme.md
**App name:** QuickWall
**Repo or homepage link:** [QuickWall](https://github.com/deepjyoti30/QuickWall)
**Description:** Set the latest wallpapers from Unsplash directly from the commandline.
**Why you think it's awesome:** Because it does not just use Unsplash's free endpoint to get a random wallpaper, it uses their API to get the latest wallpapers. Supports searching with keywords.
Supports different wallpaper setters like nitrogen, feh etc.
> Added app QuickWall

- readme.md
**App name:**
gitmoji-changelog
https://github.com/frinyvonnick/gitmoji-changelog
Changelog generator for repositories using gitmoji commit convention
I use gitmoji on each of my projects. I find it useful to have a changelog to warn users about changes at each versions of my project. I believe this could be useful to anyone using gitmoji.
**Demo:**
> Add gitmoji-changelog

- readme.md
**App name:**
tuir
https://gitlab.com/ajak/tuir
Text-based interface (TUI) to view and interact with Reddit from the terminal. 
It's really just a replacement for RTV, which has discontinued. As far as I'm aware, they work near identically.
> Replace defunct RTV with tuir

- readme.md
**App name:**
[readme-md-generator](https://github.com/kefranabg/readme-md-generator)
[https://github.com/kefranabg/readme-md-generator](https://github.com/kefranabg/readme-md-generator)
CLI that generates beautiful README.md files.
readme-md-generator will suggest you default answers by reading your package.json and git configuration.
Because it's:
- simple to use 
- smart
- allows to quickly create a good looking readme file
> Add readme-md-generator

- readme.md
I always install it to all my machines. I love the author for good sense of style.
> Add translate-shell

- readme.md
---
Hi, thanks for your time and effort for maintaining this useful list. I have fixed a typo and spelling, and improved vague description to help the readers.
> Housekeeping

- readme.md
https://github.com/Canop/broot
broot: a fast fuzzy finder created with Rust.
I know there are already a couple fuzzy finders listed, but the whale-spotting feature that broot has is interesting and makes it easy to identify directories taking up a lot of space. Not sure if that alone warrants it being added, but I figured I would at least bring it to your attention.
> Added broot

- readme.md
**Repo or homepage link:** https://github.com/sggts04/dankcli
**Description:** dankcli is a CLI Image Captioning Tool or Meme Generator which automatically adds white space and text to the top of your image.
The concept of not having to open an image editor to make a meme and a CLI handling all the text wrapping and sizing to produce a meme, is what makes it amazing.
> Add dankcli

- readme.md
https://github.com/Trendyol/docker-shell
docker-shell is an interactive prompt for docker commands written in go.
It has features like searching images, suggesting port mappings, suggest containers to start stop command etc..
> Add docker-shell

- readme.md
https://github.com/JPeer264/node-semantic-git-commit-cli
It is basically a CLI to keep semantic git commits.
It will ensure that contributors and co-workers commit with the correct guidelines.
> Add semantic-git-commit-cli

- readme.md
https://github.com/ajeetdsouza/zoxide
`zoxide` is a full-featured directory jumper written in Rust.
`zoxide` is much faster alternative than alternatives like `autojump` and `z`, and is also more feature rich. It is currently under active development, and new features are added every day!
> Add zoxide

- readme.md
- [✔︎] I've read the [contribution guidelines](https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md).
https://github.com/roma-guru/ricksay
Rick & Morty quotes of the day with ponies included!
Rick and Morty is quite popular among geeks like us.
> Add app - ricksay

- readme.md
- [ x ] I've read the [contribution guidelines](https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md).
https://github.com/imsnif/bandwhich
Bandwhich is a terminal bandwidth utilization tool that tracks your bandwidth by process, remote ip and connection. It's responsive to the terminal window, giving you more information if there is more room for it.
I find it useful, simple and approachable. But I also developed it, so I might be a little biased. :)
> Add bandwhich

- readme.md
https://github.com/kurolabs/stegcloak
StegCloak is a pure JavaScript steganography module designed in functional programming style, to hide secrets inside text by compressing and encrypting the secret before cloaking it with special Unicode invisible characters. It can be used to safely watermark strings, invisible scripts on webpages, texts on social media, or for any other covert communication.
It bypasses all character blacklists on the internet including the most important ones like Tweets, Gmail, Whatsapp, Telegram, Instagram, Facebook, etc.
Serves as the perfect and complete Unicode exploit that is available as a CLI tool #1 in topic Steganography 
Recent Practical Usecase:
Protecting copyrights by …
> Add stegcloak

- readme.md
**Repo or homepage link:** [renameutils](https://www.nongnu.org/renameutils/)
The file renaming utilities are a set of programs designed to make renaming of files faster and less cumbersome.
I use it for mass renaming files in vim, utilizing `:%s` and macros.
> Add renameutils

- readme.md
**Repo or homepage link:** https://github.com/Akianonymus/gdrive-downloader
**Description:** Cli tool for downloading gdrive files and folders. It is compatible with all POSIX shells and requires a minimal external programs.
**Why you think it's awesome:** I find it awesome because it doesn't need any authentication to download, unlikely any other tool available. In addition to that, it can also recursively download folders. It also have self update and auto-update feature, so no need to worry for updates too.
> Add gdrive-downloader

- readme.md
https://github.com/zacanger/git-all-branches
Improved `git branch -a` which shows remove branch (local only, local and remote, remote only)
It's a super handy utility that I wrote to emulate `legit branches` from [legit](https://github.com/frostming/legit), since that was the only command I found useful in `legit` itself.
> Add git-all-branches

- readme.md
visidata - A spreadsheet multitool for exploring and arranging data (csv/json/xml/xls/yaml/etc)
https://github.com/saulpw/visidata
A spreadsheet multitool for exploring and arranging data (csv/json/xml/xls/yaml/etc)
It makes exploring and modifying data (csv, json, yaml, html tables) very easy.  It is very responsive and makes it easy to filter data.
> visidata -  A spreadsheet multitool for exploring/changing data

- readme.md
https://github.com/snowtrack/snowfs
SnowFS is a lightweight command-line application and library with a focus on binary file versioning
It is an alternative to Git, bringing in some fresh wind ;-)
> Add SnowFS

- readme.md
**Repo or homepage link:** [https://github.com/ZacharyTalis/awesome-cli-apps](https://github.com/ZacharyTalis/awesome-cli-apps)
**Description:** Currently, the Table of Contents doesn't contain a link to the Docker section. This should fix it :)
**Why you think it's awesome:** n/a, see above.
> Add Docker to Table of Contents

- readme.md
**Repo or homepage link:** https://dianne.skoll.ca/projects/remind
**Description:** Remind is a sophisticated calendar and alarm program.
**Why you think it's awesome:** 
- Powerful and expressive DSL for defining events.
- Great support for recurrence.
- Can generate postscript and html calendars for printing (to paper).
- Licensed under GPLv2.
- (Ships with a GUI if you really need one.)
> Add remind

- readme.md
**Repo:** https://github.com/kha7iq/pingme
**Docs:** https://pingme.lmno.pk
PingMe is a CLI tool which provides the ability to send messages or alerts to multiple messaging platforms & email.
Being built with go it can be shipped easily anywhere. 
Its use cases are sending alerts from backup scripts, cron jobs , ci/cd pipelines and anywhere else depending on use cases.
Its one stop shop for sending alerts, or messages. Multi architecture and and multi platform.
Supports sending messages, push notifications, sms, and supports multiple platforms.
Also available as a GitHub Action.
Currently supported
- Discord
- Email
- Microsoft Teams
- Mattermost
- Pushover
- Pushbullet
- RocketChat
- Slack
- Telegram
- Twillio
> Add pingme

- readme.md
https://gitlab.com/FixFromDarkness/organize-rt
Rust copy of organize-cli with more customization, undo and more
Faster than organize-cli, more customization
> Add organize-rt

- readme.md
**Repo or homepage link:** https://github.com/imsnif/diskonaut
**Description:** A visual disk space navigator for linux/mac/windows. It draws a tree-map in the terminal representing the disk space of a given folder (or the entire hard-drive), allowing you to delete files/folders and tracking how much disk space was freed in the current session.
**Why you think it's awesome:** I find it easier to visualize disk space utilization rather than looking at a list of numbers. Diskonaut does that for you in the terminal, and even lets you look at the map being drawn while it's still scanning. (full disclosure: I am the original author).
> Add diskonaut

- readme.md
**Repo or homepage link:** https://github.com/achannarasappa/ticker
**Description:** Terminal stock ticker with live updates and position tracking.
**Why I think it's awesome:** Ticker makes it easy for terminal users to check in on their stock or crypto positions without leaving their terminal. There's also the ability to customize the interface and support for international currencies.
> Add ticker

- readme.md
**Repo or homepage link:** https://github.com/juan-leon/lowcharts
**Description:** Draw low-resolution graphs in terminal.
**Why I think it's awesome:** I can analyze all kind of logs and text based data quickly and without leaving the terminal.
> Add lowcharts

- check-for-deprecation.sh
- readme.md
- remove found deprecated apps
closes #330
> Add script for checking apps for deprecation

- readme.md
**Repo or homepage link:** https://github.com/nschloe/tiptop
**Description:** A command-line "graphical" system monitor
**Why I think it's awesome:** Graphics on the command line is always cool, and even more so if it show actually useful info.
> Add tiptop

- readme.md
https://ohmyposh.dev
https://github.com/JanDeDobbeleer/oh-my-posh
Prompt theme engine for any shell and platform.
I created it so I might be biased, but there seems to be a lot of love from others as well so why not share the news.
> Add oh-my-posh

- readme.md
**Repo or homepage link:** https://github.com/nikolassv/bartib
**Description:** "A simple timetracker for the command line "
**Why I think it's awesome:** It's an easy to use time tracking tool that allows you to create flexible reports and saves its log in a plaintext file.
> Add Bartib

- readme.md
https://github.com/ZinoKader/portal
Portal is a quick and easy command-line file transfer utility to send files from any computer to another, locally or over the internet.
If you're ever in a situation where you want send a file over to a friend or coworker quickly, without having to worry about file size limits, file type limits or slow transfers (even though you're right next to each other!), then Portal is a great CLI tool to use.
All communication beyond the initial client handshake is encrypted. If the sender and receiver can reach each other directly, the file transfer involves no servers. Otherwise the file transfer goes through a relay server which facilitates the connection, but sees none of the data.
> Add portal

- readme.md
**Repo or homepage link:** https://github.com/talwat/pokeget
**Description:** pokeget is a bash script that displays sprites of pokemon in your terminal. You can display small sprites, large sprites, and more.
pokeget is awesome because its only dependencies are bash, cURL, and the GNU coreutils. You can include the output in screenshots of your desktop, and you can also use it to quickly get the original sprite of any pokemon you want for reference.
> Add pokeget

- readme.md
[Pokete](https://github.com/lxgr-linux/pokete)
A terminal based Pokemon like game.
I's a fully featured Pokemon like game for the terminal, with ASCII-Art, music and much more to offer. And it is GPL-v3.
I hope this is a good place for it.
> Add pokete

- readme.md
wttr.in
- [ x] I've read the [contribution guidelines](https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md#readme).
**Repo or homepage link:** https://github.com/chubin/wttr.in
**Description:**  The right way to check the weather
**Why I think it's awesome:** Weather in terminal :D
> Add wttr.in

- readme.md
https://github.com/s0rg/crawley
Unix-way web crawler.
Fast, full-featured, 100%-test covered.
> Add crawley

- readme.md
- I tried to move stuff out the generic utilities collection into more specific sub categories as much as possible.
- Created some sub categories
- Remove the "leftovers" `Other` category
- Removed unfitting or low star count repos
> Overhaul utilities section

- readme.md
- remove Web Development category and refactor contents in to Frontend and HTTP Server/Client categories
> Overhaul Development category

- readme.md
Signed-off-by: Olivier Vernin <olivier.vernin@suse.com>
https://github.com/updatecli/updatecli
Updatecli is a declarative dependency management tool used to automatically update git repositories
It allows to automate git repositories update which makes long term maintainability easier.
> Add updatecli

- readme.md
**Repo or homepage link:** https://github.com/maaslalani/slides
**Description:** Terminal based presentation tool
I think slides is awesome because it's really easy and straightforward to make presentations in markdown with it. I think it deserves a spot on this list
> Add slides

- readme.md
https://github.com/yt-dlp/yt-dlp
A `youtube-dl` fork with additional features and fixes.
It carries the awesomeness from `youtube-dl`, added additional features `youtube-dl` doesn't have, fixed issues `youtube-dl` had, and more importantly it is actively maintained compared to `youtube-dl`.
> 39 Pull requests merged by 26 people
Excluding merges, 28 authors have pushed 56 commits to master and 56 commits to all branches. On master, 47 files have changed and there have been [3,561 additions and 1,009 deletions](https://github.com/yt-dlp/yt-dlp/compare/68be95bd0ca3f76aa63c9812935bd826b3a42e53...master).
Compared to `youtube-dl`...(same one month view)
> 1 Pull request merged by 1 person
Excluding merges, 2 authors …
> Add yt-dlp

- readme.md
- [x ] I've read the [contribution guidelines](https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md#readme).
**Repo or homepage link:** https://github.com/clevercli/clevercli
**Description:** A collection of ChatGPT powered utilities.
**Why I think it's awesome:** An AI directly in your shell. Also, no more fighting with man pages.
> Add clevercli

- readme.md
Repo: https://github.com/ast-grep/ast-grep
Homepage: https://ast-grep.github.io/
**Description:** 
A tool using abstract syntax tree to structure search and refactor code.
ast-grep searches and rewrites code based on AST. It is a structural search/replacement CLI tool. It is more powerful and precise than using regular expressions or text-based tools. 
ast-grep is fast and reliable, as it is written in Rust and uses tree-sitter for parsing and matching. 
It is a great tool for doing lightweight static analysis and massive-scale code refactoring.
> Add ast-grep

- readme.md
https://github.com/parvardegr/sharing
Sharing is a command-line tool to share directories and files from the CLI to iOS and Android devices without the need of an extra client app
I use it everyday, it's pretty handy and also it does not require any extra app on my phone
> Add sharing

- readme.md
https://github.com/jesseduffield/lazygit
simple terminal UI for git commands
It is an awesome tool for those who don't like to type git commands manually.
> Add lazygit.

- readme.md
https://github.com/mk-5/fjira
Fjira is a terminal user interface for Jira. It provides a fuzzy-search approach to interact with Jira tickets. Its key features are:
- Exploration of Jira Projects and Issues
- Quick modification of Jira Issue assignees
- Quick modification of Jira Issue statuses
- Easy commenting on Jira tickets
- Ability to manage multiple workspaces (Jira URLs)
- Jira Issue search using custom JQL expressions
You can do your daily Jira stuff directly from your terminal - that's awesome 😄 
And let's be real, haven't we all been there? Navigating between Jira tickets in a browser, it can get pretty frustrating. With Fjira, that hassle is history.
> Add fjira.

- readme.md
https://github.com/deep5050/radio-active
An internet radio player with 40000+ stations.
- It has over 40K radio stations!
- Simple and clean UI
- Lightweight
> added radioactive: An internet radio player

- readme.md
> fix typo in clevercli description

- readme.md
https://github.com/rs/curlie
Frontend to curl with the ease of use of httpie without compromising on performance and features.
Curlie stands out as an exceptional command-line HTTP client that combines the best attributes of HTTPie and curl. Its commitment to ease of use, real-time output formatting, transparent command insights, and performance optimization makes it an excellent choice for developers and users who require a versatile and efficient tool for interacting with HTTP services.
> Add curlie

- readme.md
I really enjoyed using this project, nice work! Caught a couple of typos in the readme.md though 😛
> Fix typos in descriptions and links

- check-for-deprecation.sh
- readme.md
https://github.com/magicmonty/bash-git-prompt
Just looks at this
Increase productivity - with this I need less `git status`. I use it for years. Easy to install. Many stars. Having time is also useful - when I read previous commands I can understand, for example, how long of time tests took, or when I ran it.
> Add bash-git-prompt

- readme.md
https://github.com/starship/starship
Minimal, blazing-fast, and infinitely customizable prompt for any shell.
I use it everyday, it's fancy, available presets are nice and working out-of-the-box.
It gives relevant information about Git and current project environment in most languages (python, node, ...).
> Add starship
