agarrharr/awesome-cli-apps

README.md

This tool allows you to do simple and complex screencasts.
* Chosse monitor (if multiple monitors are connected)
* Sound and camera overlay are optional
* Possibility to read out camera resolution (OSX & Linux)
* Possibility to just list the corresponding ffmpeg command (dry-run)

Adding ffscreencast for easy screenrecording (Linux & OSX)

---

README.md

Added [dev-time](https://github.com/samverschueren/dev-time-cli) to the utilities list. Not sure if it's the correct section though, didn't knew where else to put it.

add dev-time

---

README.md

[diff2html-cli](https://github.com/rtfpessoa/diff2html-cli) is an easy to use command-line tool that parses git diffs to JSON and also generates pretty HTML. 
The tool allows better code comparisons, optimized with line-by-line and side-by-side views, new and old line numbers, inserted, removed and edited lines identification, GitHub like style, code syntax highlight and line similarity matching.

Add diff2html-cli to Command-line tools

---

README.md

share-cli is designed to share files with people on your LAN real quick. Think of it as replacment for sharing files via USB stick. 
*  easy installation via npm
*  extremely simple usage

Add share-cli

---

README.md

remote-share-cli is designed to share files with people via the web real quick. 
It starts a local http server streaming the contents of exactly one file and exposes the server via `localtunnel.me`.

Add remote-share-cli

---

README.md

Football CLI helps you get live scores, fixtures, standings and more of almost every football competition/league in your terminal.
Github link: https://github.com/ManrajGrover/football-cli

Adds Football CLI

---

README.md

This might look the existing `log-update`, but it's more simple and accepts multiple updates concurrently.
The Gif says what it does, and the docs even more: [https://github.com/ivanseidel/node-draftlog](https://github.com/ivanseidel/node-draftlog)

Add DraftLog to the list of Command-line utilities

---

README.md

Moro is a simple time tracker, that has only one command: moro. It's perfect for nine to five jobs with flexible hours. If you can read german, this magazine has written a nice article about it: t3n [link](http://t3n.de/news/kommandozeile-terminal-time-tracking-zeiterfassung-803805/)
I started it for my own use, but after the article got published I guessed it might be useful for others too.

Add Moro, the time tracker

---

README.md

googler is a power tool to Google (Web & News) and Google Site Search from the command-line.
Features:
- Google Search, Google Site Search, Google News
- Fast and clean (no ads, stray URLs or clutter), custom color
- Navigate result pages from omniprompt, open URLs in browser
- Effortless keyword-based site search with googler @t add-on
- Fetch n results in a go, start at the n<sup>th</sup> result
- Disable automatic spelling correction and search exact keywords
- Specify duration, country/domain (default: worldwide/.com), language
- Google keywords (e.g. `filetype:mime`, `site:somesite.com`) support
- Open the first result directly in browser (as in *I'm Feeling Lucky*)
- Non-stop searches: fire new searches at omniprompt without exiting
- HTTPS proxy, User Agent, TLS 1.2 (default) …

Add googler

---

README.md

A Node.js CLI app that displays status of your Google Wifi / OnHub router. https://www.npmjs.com/package/google-wifi-status

Add google-wifi-status

---

readme.md

The old library described just implemented a cli on top of https://github.com/ddsol/speedtest.net. They now support a cli and there is no need for another cli that uses the original same repo.

Old Library was just a Wrapper

---

readme.md

This is a utility that allows developers to quickly fetch news headlines from the terminal via the `curl` command, similar to wttr.in.

Add getnews.tech

---

readme.md

I have added the project `papis` to the productivity list.
`papis` is a way of organizing documents (books, papers, even music and videos)
in a very simple way. 
It is designed to be modular (write scripts like in `git`), play well with
tools like `git` and to make people feel that they can take full control of their libraries
(in contrast with `zotero`, `mendeley` and the like).
It is specially well-suited for authors and researchers.
- Big disclaimer: I am the main contributor.
- Why: It is currently being used by some people and there is no similar software in the list
currently.

Add papis to productivity section

---

readme.md

Splash Cli is a command-line utility to manage and download wallpapers from [unsplash](http://unsplash.com) from terminal. 
Learn more [here](https://github.com/rawnly/splash-cli)

Added splash-cli

---

readme.md

[undollar](https://github.com/ImFeelingDucky/undollar) makes copy-pasting commands from the internet easier. If the command includes a leading dollar sign, undollar removes it and runs the rest of the command.

Add undollar

---

readme.md

lstags is a utility and an API to manipulate (analyze, synchronize and aggregate) images across different Docker registries.
https://github.com/ivanilves/lstags

Utility to manipulate images in Docker registries

---

readme.md

[https://github.com/mixn/carbon-now-cli](https://github.com/mixn/carbon-now-cli)
The feedback for this tool I made was quite overwhelming and the tool itself seems quite useful to many. So I thought it might be a good fit for this list. :)

Adds carbon-now-cli

---

readme.md

[Discharge](https://github.com/brandonweiss/discharge) is, as far as I’m aware, the easiest way to deploy static websites to Amazon S3. It can also configure an SSL certificate and distribute the site via CloudFront, all without having to know anything about AWS. I spent hours poring over AWS’s terrible docs so no one else would have to. There is also a prompt-based UI to help you configure it. And it’s very well documented.
Thanks for considering!

Add Discharge

---

readme.md

**Update**
[Terminal velocity](https://terminal-velocity-notes.github.io/terminal_velocity/)
I noticed the URL currently provided no longer works. New URL is provided above.
**Add**
[sncli](https://github.com/insanum/sncli) - Simplenote Command Line Interface
sncli is a Python application that gives you access to your Simplenote account via the command line. You can access your notes via a customizable console GUI that implements vi-like keybinds or via a simple command line interface that you can script.
Very handy and configurable... I wouldn't go a day without it.
Does not have a LICENSE file provided on the repo, but upon further inspection it is in fact licensed under the MIT license.
Thanks!

Update URL for Terminal velocity. Add sncli to Productivity.

---

readme.md

`speed-test` wasn't added as a new list item. Fixed this by changing `--` to `-`
Added `speedtest-cli` as well. Install in one of the ways:
- `wget -O speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
chmod +x speedtest-cli`
- `curl -Lo speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
chmod +x speedtest-cli`
- `pip install speedtest-cli`
- `easy_install speedtest-cli`
- `pip install git+https://github.com/sivel/speedtest-cli.git`

FIX speed-test and ADD speedtest-cli

---

readme.md

[package link](https://github.com/snwfdhmp/simplehttp)
I think this package can be useful for web developers when they need to quickly serve some files over http from CLI without wanting to configure at least an Apache or NGINX.

Add simplehttp

---

readme.md

Copy of #221 
Creates large characters out of ordinary
screen characters:
```
_            _     _      _ 
(_)_ __   ___(_) __| | ___| |
| | '_ \ / _ \ |/ _` |/ _ \ |
| | | | |  __/ | (_| |  __/ |
_/ |_| |_|\___|_|\__,_|\___|_|
|__/                           
```
[**repo**](https://github.com/cmatsuoka/figlet) [**site** (better example)](http://www.figlet.org/)
Install:
```bash
$ brew install figlet
$ pacman -S figlet
```

Add figlet

---

readme.md

Implements #105
**App name:**
Newsboat
[repo](https://github.com/newsboat/newsboat)
An extendable RSS feed reader for text terminals.
Very flexible RSS feed app. I use it for watching youtube (a channels uploads are available as RSS feed, which I then watch in vlc), as well as downloading podcasts.

Add newsboat

---

readme.md

Server management (Apache, NGIX) falls more into the **Devops** section than the **Web Development** section.

Move htconvert into Devops

---

readme.md

https://github.com/darrikonn/td-cli
**td-cli** is a command line todo manager, 
where you can organize and manage your todos across multiple projects
**td-cli** allows you to group your todos based on your projects and helps you keep your todos well organized and well structured.
**td-cli** also has an awesome interactive mode which speeds up the whole process!
```bash
pip3 install td-cli
```

Add td-cli to productivity

---

readme.md

**App name:** npm-check-updates
**Repo or homepage link:**[repo](https://github.com/tjunnone/npm-check-updates)
Find newer versions of package dependencies than what your package.json allows
It's default is a dry run (i.e. it prints out new version that will be upgraded):
```
jsonwebtoken     ^8.4.0  →     ^8.5.0 
mongoose        ^5.4.13  →    ^5.4.17 
@types/helmet    0.0.42  →     0.0.43 
@types/jest     ^24.0.5  →    ^24.0.9 
@types/node     ^11.9.4  →   ^11.10.5 
jest            ^24.1.0  →    ^24.3.1 
ts-jest        ^23.10.5  →    ^24.0.0 
ts-node          ^8.0.2  →     ^8.0.3 
typescript       ^3.3.3  →  ^3.3.3333
```
It allows for exclusion of updates, and is all in all way more predictable than `npm upgrade`.

Add npm-check-updates

---

readme.md

There are a few npm related apps, which could be grouped together.
This would be the first category 2 levels deep (i.e. Development>Web Development>npm).

Add 'npm' subcategory

---

readme.md

Cleanup and normalize the app descriptions more. Remove marketing jargon (beautiful, powerful, etc.)  and unnecessary descriptions (cli, command-line, in the terminal, etc.).
See [files](https://github.com/agarrharr/awesome-cli-apps/pull/305/files) and notes for examples.

Cleanup descriptions

---

readme.md

**App name:**
lazydocker
https://github.com/jesseduffield/lazydocker
A simple terminal UI for both docker and docker-compose.
I tried both dockly (already listed) and lazydocker.
While both work very well, lazydocker is more user-friendly.

Add lazydocker

---

readme.md

`Terminal Utils` does not say anything `Terminal Sharing` is more descriptive.

Rename 'Terminal Utils' to 'Terminal Sharing Utils'

---

readme.md

**App name:**
sqlline
https://github.com/julianhyde/sqlline 
Shell for issuing SQL to relational databases via JDBC 
Currently it has more than 250 stars and continues growing. It could connect to any db via jdbc driver and not only db (e.g. it could connect to elastic-search, cassandra, splunk, mongo, kafka via apache calcite). It provides autocompletion, syntax highlighting, multiline editing(emacs/vi modes), dialect supports. 
Besides project Readme.md there is also a set of video demos with that at asciinema.org https://github.com/julianhyde/sqlline/wiki/Demos

Add sqlline

---

readme.md

**App name:**
spotify-tui
https://github.com/Rigellute/spotify-tui
Terminal user interface for spotify.
This app offers a fast, lightweight, portable terminal user interface for Spotify. Intended for users that don't want to leave the terminal. 
The app makes use of familiar vim & tmux keybindings.

Add spotify-tui

---

readme.md

**Repo or homepage link:** https://github.com/bntzio/wipe-modules
**Description:** Easily remove the `node_modules` folder of non-active projects.
**Why you think it's awesome:** [wipe-modules 🗑️](https://github.com/bntzio/wipe-modules) is a CLI tool to delete all the `node_modules` of your projects at once, allowing you to get back a decent amount of hard-disk space.

Add wipe-modules

---

readme.md

- https://github.com/laixintao/iredis
- https://iredis.io
Interactive Redis: A Terminal Client for Redis with AutoCompletion and Syntax Highlighting.
- Advanced code completion. If you run command `KEYS` then run `DEL`, IRedis will auto-complete your command based on `KEYS` result.
- Command validation. E.g. try `CLUSTER MEET IP PORT`, iredis will validate IP and PORT for you.
- Command highlighting, fully based on redis grammar. Any valid command in IRedis shell is a valid redis command.
- Human-friendly result display.
- `peek` command to check the key's type then automatically call `get`/`lrange`/`sscan`, etc, depending on types. You don't need to call the `type` command then type another command to get the value. `peek` will also display the key's length and memory …

Add iredis

---

readme.md

**App name:** import-github-labels-cli
**Repo or homepage link:** https://github.com/abhijithvijayan/import-github-labels-cli
**Description:** CLI to import labels from another repository on GitHub 
**Why you think it's awesome:** Sometimes when a user needs to import / manage GitHub labels used in one project to another in a single command, this CLI does it neat & perfect.

add import-github-labels-cli

---

readme.md

**Repo or homepage link:** 
https://github.com/labbots/google-drive-upload
Google Drive Upload (gupload) is a  cli tool that enables users to upload files and folders to google drive from command line. It also has ability to upload files in parallel and resume interrupted uploads.
It allows users to upload files and folders to the user's google drive from command line. The script can also be used as part of CI to push artifacts into google drive and share it with anyone.

Added google drive upload to Productivity

---

readme.md

**Repo or homepage link:** https://github.com/SwagLyrics/SwagLyrics-For-Spotify
Fetches the currently playing song from Spotify on Windows, Linux and macOS and displays the lyrics in the command-line, browser tab or in a desktop application. Refreshes automatically when song changes. The lyrics are fetched from Genius. Turns out Deezer already has this feature in-built but with swaglyrics, you can have it in Spotify as well.
wagLyrics is the fastest and the most accurate package for getting lyrics.1
Provided optimal internet, SwagLyrics can fetch lyrics for a track in as less as 0.28s.2
It also does not require the user to generate any sort of API token (Spotify or Genius) and serves functionality right off the bat. This is possible as the song identification is done …

Add swaglyrics

---

readme.md

…ADME.md file from the current directory to a container registry like Docker Hub.
https://github.com/christian-korneck/docker-pushrm
[docker-pushrm](https://github.com/christian-korneck/docker-pushrm) is a Docker CLI plugin that pushes the README file from the current directory to a container registry where it appears as repo description. Supports Docker Hub, Quay Harbor.
I've always liked that with Docker you can push an image to Docker Hub (or other container registries) even if the repo for it doesn't exist yet (it gets created on the fly).
docker push myuser/myimage:tag
With docker pushrm, a little CLI plugin for Docker, it's now possible to set or update the README of the repo in the same style:
```
$ ls …
```

Add docker-pushrm

---

readme.md

**Repo or homepage link:** https://github.com/derailed/k9s / https://k9scli.io
**Description:** Kubernetes CLI to manage your clusters in style.
I was surpised not to see k9s in this list, as it's the most impressive CLI app I've ever used !
It's very popular among kubernetes users (11.5k stars), because it's both intuitive and very complete feature-wise
It is also the only CLI tool which can totally replace `kubectl`

Add k9s to Devops

---

readme.md

**App name:** gopass
**Repo or homepage link:** https://github.com/gopasspw/gopass
**Description:** gopass is a fully-featured command line password manager written in Go. It has support for teams/remote syncing, multiple stores, fuzzy-finding, a JSON API, and more.
**Why you think it's awesome:** It's similar to the proven `pass` command line app but with many extra features that make is useful, especially if you want your password stores available to multiple users or on multiple computers.
This PR replaces #358.

Add gopass

---

readme.md

https://github.com/Hakky54/certificate-ripper
A simple way to extract and analyse server certificates for either testing purposes or just analysing the content of it.
It has a capability of resolving all of the certificates up to the root certificate even when it is not provided by the server. Which is not possible with openssl. And it is lightning fast 😄 
Some awesome capabilities:
- Extracting and mapping it into a p12 truststore file
- Printing it as human readable
- Printing it in PEM format
- Bulk extraction of multiple different websites in a single command

Add Certificate Ripper

---

readme.md

_Disclaimer:_ I wrote deadlink.
https://github.com/nschloe/deadlink
[deadlink](https://github.com/nschloe/deadlink) finds and fixes dead links (and redirects) in files.
Does one thing and does it well: Finds dead links in codes files, `README.md`s etc. Running it on this `readme.md` gives
```
Successful permanent redirects (14):
301:   http://taskwarrior.org
→ 200: https://taskwarrior.org/
301:   http://calcurse.org/
→ 200: https://calcurse.org/
301:   https://i.creativecommons.org/p/zero/1.0/88x31.png
→ 200: https://licensebuttons.net/p/zero/1.0/88x31.png
301:   http://ledger-cli.org
→ 302: https://ledger-cli.org/
301:   https://www.nongnu.org/renameutils
→ 200: https://www.nongnu.org/renameutils/
301: …
```

Utilities: add deadlink

---

readme.md

`papis` repository URL was a fork and not the official one.

Fix papis repository URL

---

readme.md

It currently redirects to https://github.com/agarrharr/awesome-cli-apps/blob/master/caniuse.com

Fix the caniuse.com link

---

readme.md

**Repo or homepage link:** https://github.com/poetaman/arttime
**Description:** Featureful timer with native desktop notifications and curated ASCII art.
**Why I think it's awesome:** Runs with zero dependencies on macOS and minimal dependencies on other OSes. This shell script timer tool brings a dash of curated ASCII / UTF art to developer terminals, while offering functionality of timer. Users can also set a time manager program tailored to their needs such that Pomodoro technique is just one of the multitude of possibilities . Please refer to manual ``arttime -m`` and the github repo for more information and design philosophy.

Add arttime
